export let students = [
  {
    id: 1,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 2,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 3,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 4,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 5,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 6,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
  {
    id: 7,
    studentname: "Nguyen Van A",
    classname: "10A1",
    behaviorpoint: 10,
    discipline: 10,
    title: 10,
    GPA: 10,
  },
]
